version: '3.3'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
#    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-data:/etc/openvpn
    environment:
      - OVPN_SERVER_URL=udp://45.89.190.130
      - OVPN_CN=45.89.190.130
      - OVPN_PROTO=udp
      - OVPN_NAT=1
    restart: always